# Generated by Django 5.2 on 2025-04-09 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_rename_date_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='name',
            new_name='pet_name',
        ),
        migrations.AddField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
